name: Deploy Portfolio
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Cloudflared on Runner
        run: |
          curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cloudflared
          chmod +x cloudflared
          sudo mv cloudflared /usr/local/bin/

      - name: Deploy via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ssh.kunjidev.shop
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          # This tells GitHub to use the cloudflared tool to enter the tunnel
          proxy_host: ssh.kunjidev.shop
          proxy_command: /usr/local/bin/cloudflared access ssh --hostname %h
          source: "index.html,style.css,script.js,pdfs/*,img/*"
          target: "/data/data/com.termux/files/usr/share/nginx/html/"